### ISSUE TITLE
Issues / annoyances with `csnx` repo

### ISSUE THREAD

**Issue by jamesmockett** [guardian/csnx#1121]
- [ ] Running `make storybooks` results in `apps/csnx/package.json` being created.
- [ ] All 3 Source packages have the same error in `tsconfig.json`:
  > Cannot write file '/csnx/.storybook/main.js' because it would overwrite input file`
- [ ] Stories using the Backgrounds addon may fail colour contrast checks when running locally and the story is first opened. https://github.com/storybookjs/storybook/issues/25257)

**Comment by SiAdcock** [comment]
> All 3 Source packages have the same error in tsconfig.json:

I'm not able to recreate this error, although admittedly I don't know where to look 😅 I've tried

- `make storybook`
- `make validate`
- viewing the `tsconfig.json` for each Source project in my editor

> Stories using the Backgrounds addon may fail colour contrast checks when running locally and the story is first opened.

The linked issue has been resolved, so maybe this has been fixed. 

Unfortunately the Accessibility pane is currently giving me the following error message for all stories 🤦‍♂️

```
The accessibility scan encountered an error.
{"name":"TypeError"}
```

**Comment by sndrs** [comment]
confirm if this is still an issue

**Comment by jamesmockett** [comment]
I'm no longer seeing the error in `tsconfig.json` so this seems to be fixed. (I was seeing it in VS Code where the file was highlighted in red to indicate an error and the `"path": "./tsconfig.spec.json"` line had a red squiggly which would show the error from the description on hover.)

**Comment by jamesmockett** [comment]
The colour contrast check is still an issue. You can see it on the Inline Error component with the Brand theme selected:
https://main--635a6fffacd30d393597c1ff.chromatic.com/index.html?path=/story/inlineerror--inline-error-brand-theme&globals=viewport:responsive

Because the background fades from white to blue the contrast check happens during an intermediate state. If you switch from the _Accessibility_ tab and back again it reruns the check and passes because there's no fade.

**Comment by SiAdcock** [comment]
Thanks for the explainer @jamesmockett. To me that sounds like a bug in the accessibility plugin rather than something in our setup. What are the next steps? And is this currently blocking anything from our perspective?
